<a href="https://colab.research.google.com/github/preekshitsaklani/titanic-dt/blob/main/Decision_Trees_Titanic_Survivors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Mounting Google Drive

In [ ]:
from google.colab import drive

## Loading the data

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive

## Readind the data

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/train.csv")

## Displaying first 5 rows

In [ ]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## Displaying data information

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

## Columns to drop

In [ ]:
columns_dropped=['PassengerId','Name','Ticket', 'Cabin']

## Dropping columns

In [ ]:
data= data.drop( columns_dropped , axis =1)

## Displaying data after dropping columns

In [ ]:
data.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

## Importing LabelEncoder

In [ ]:
from sklearn.preprocessing import LabelEncoder

## Encoding 'Sex' column

In [ ]:
label_enc= LabelEncoder()

data['Sex']= label_enc.fit_transform(data['Sex'])

## Encoding 'Embarked' column

In [ ]:
data['Embarked']= label_enc.fit_transform(data['Embarked'])

## Displaying data after encoding

In [ ]:
data.head()

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2

## Filling missing 'Age' values

In [ ]:
data = data.fillna(data['Age'].mean())

## Displaying data info after filling missing values

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    int64
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Embarked  891 non-null    int64
dtypes: float64(2), int64(6)
memory usage: 55.8 KB

## Defining input columns

In [ ]:
input_col=['Pclass',	'Sex'	,'Age'	,'SibSp'	,'Parch',	'Fare'	,'Embarked']

## Defining output column

In [ ]:
output_col=['Survived']

## Separating features and target

In [ ]:
X_data= data[input_col]
Y_data = data[output_col]

## Displaying shapes of data

In [ ]:
X_data.shape, Y_data.shape

((891, 7), (891, 1))

## Entropy function

In [ ]:
def Entropy(col):
    favour= np.unique(col,return_counts=True)
    N= col.shape
    ent_py=0
    for i in favour[1]:
        prob = i/N
        ent_py += -1 * (prob * np.log2(prob))
    return ent_py

## Data division function

In [ ]:
def divide_data(X_data, feat, value):
    X_left = X_data[X_data[feat] < value]
    X_right = X_data[X_data[feat]>= value]
    return X_left, X_right

## Dividing sample data

In [ ]:
left, right = divide_data(data[:10],'Sex',0.5)

## Displaying divided data

In [ ]:
left, right

(   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
 1         1       1    0  38.0      1      0  71.2833         0
 2         1       3    0  26.0      0      0   7.9250         2
 3         1       1    0  35.0      1      0  53.1000         2
 8         1       3    0  27.0      0      2  11.1333         2
 9         1       2    0  14.0      1      0  30.0708         0,
    Survived  Pclass  Sex        Age  SibSp  Parch     Fare  Embarked
 0         0       3    1  22.000000      1      0   7.2500         2
 4         0       3    1  35.000000      0      0   8.0500         2
 5         0       3    1  29.699118      0      0   8.4583         1
 6         0       1    1  54.000000      0      0  51.8625         2
 7         0       3    1   2.000000      3      1  21.0750         2)

## Information gain function

In [ ]:
def info_gain(X_data, feat, value):
    left,right= divide_data(X_data, feat, value)

    prob_l= left.shape[0]/X_data.shape[0]
    prob_r= right.shape[0]/X_data.shape[0]

    i_gain= Entropy(X_data.Survived) - (prob_l * Entropy(left.Survived) + prob_r * Entropy(right.Survived))

    return i_gain

## Calculating information gain for features

In [ ]:
for i in X_data.columns:
    print ( i , info_gain(data, i , data[i].mean()))

Pclass [0.07579363]
Sex [0.21766011]
Age [0.00115864]
SibSp [0.00958454]
Parch [0.01538075]
Fare [0.04214069]
Embarked [0.0159094]

## Decision Tree Class

In [ ]:
class Decision_Tree:
    def __init__(self, depth=0, max_depth=7):
        self.left= None
        self.right= None
        self.feat= None
        self.value = None
        self.max_depth= max_depth
        self.depth= depth
        self.target= None

    def train(self,X_train):
        f = ['Pclass',	'Sex'	,'Age'	,'SibSp'	,'Parch',	'Fare'	,'Embarked']
        i_gain=[]

        for i in f:
            i_gain.append(info_gain(X_train, i , X_train[i].mean()))

        self.feat= f[np.argmax(i_gain)]
        self.value= X_train[self.feat].mean()

        data_left, data_right= divide_data( X_train, self.feat, self.value)
        data_left= data_left.reset_index(drop= True)
        data_right= data_right.reset_index(drop= True)

        print("Making tree with feature:", self.feat, "Depth:", self.depth)


        if data_right.shape[0]==0 or data_left.shape[0]==0:
            if X_train.Survived.mean()>=0.5:
                self.target= 'Survived'
            else:
                self.target='Not Survived'
            return 'Done Training'

        if self.depth>= self.max_depth:
            if X_train.Survived.mean()>=0.5:
                self.target= 'Survived'
            else:
                self.target='Not Survived'
            return 'Done Training'

        self.left= Decision_Tree(depth= self.depth+1)
        self.left.train(data_left)

        self.right= Decision_Tree(depth= self.depth+1)
        self.right.train(data_right)

        if X_train.Survived.mean()>=0.5:
            self.target= 'Survived'
        else:
            self.target='Not Survived'
        return 'Done Training'

    def predict(self, test):
        if test[self.feat]>= self.value:
            if self.right is None:
                return self.target
            return self.right.predict(test)
        else:
            if self.left is None:
                return self.target
            return self.left.predict(test)

## Splitting data into train and test sets

In [ ]:
split=0.8

train_X= data[:int(split*data.shape[0])]
test_X= data[int(split*data.shape[0]):]
test_X= test_X.reset_index(drop= True)

## Displaying train set

In [ ]:
train_X

     Survived  Pclass  Sex        Age  SibSp  Parch      Fare  Embarked
0           0       3    1  22.000000      1      0    7.2500         2
1           1       1    0  38.000000      1      0   71.2833         0
2           1       3    0  26.000000      0      0    7.9250         2
3           1       1    0  35.000000      1      0   53.1000         2
4           0       3    1  35.000000      0      0    8.0500         2
..        ...     ...  ...        ...    ...    ...       ...       ...
707         1       1    1  42.000000      0      0   26.2875         2
708         1       1    0  22.000000      0      0  151.5500         2
709         1       3    1  29.699118      1      1   15.2458         0
710         1       1    0  24.000000      0      0   49.5042         0
711         0       1    1  29.699118      0      0   26.5500         2

[712 rows x 8 columns]

## Displaying test set

In [ ]:
test_X

     Survived  Pclass  Sex        Age  SibSp  Parch      Fare  Embarked
0           1       1    1  48.000000      1      0   52.0000         2
1           0       3    1  29.000000      0      0    9.4833         2
2           0       2    1  52.000000      0      0   13.0000         2
3           0       3    1  19.000000      0      0    7.6500         2
4           1       1    0  38.000000      0      0  227.5250         0
..        ...     ...  ...        ...    ...    ...       ...       ...
174         0       2    1  27.000000      0      0   13.0000         2
175         1       1    0  19.000000      0      0   30.0000         2
176         0       3    0  29.699118      1      2   23.4500         2
177         1       1    1  26.000000      0      0   30.0000         0
178         0       3    1  32.000000      0      0    7.7500         1

[179 rows x 8 columns]

## Initializing Decision Tree

In [ ]:
dt= Decision_Tree( max_depth = 10)

## Training the Decision Tree

In [ ]:
dt.train(train_X)

Making tree with feature: Sex Depth: 0
Making tree with feature: Pclass Depth: 1
Making tree with feature: Embarked Depth: 2
Making tree with feature: Age Depth: 3
Making tree with feature: Pclass Depth: 4
Making tree with feature: Pclass Depth: 5
Making tree with feature: Pclass Depth: 5
Making tree with feature: Age Depth: 4
Making tree with feature: Pclass Depth: 5
Making tree with feature: SibSp Depth: 5
Making tree with feature: Fare Depth: 6
Making tree with feature: Pclass Depth: 7
Making tree with feature: Pclass Depth: 7
Making tree with feature: Pclass Depth: 6
Making tree with feature: Age Depth: 3
Making tree with feature: SibSp Depth: 4
Making tree with feature: Age Depth: 5
Making tree with feature: Pclass Depth: 6
Making tree with feature: Pclass Depth: 7
Making tree with feature: Pclass Depth: 7
Making tree with feature: Age Depth: 6
Making tree with feature: Age Depth: 7
Making tree with feature: Pclass Depth: 7
Making tree with feature: SibSp Depth: 5
Making tree with feature: Pclass Depth: 6
Making tree with feature: Fare Depth: 7
Making tree with feature: Age Depth: 7
Making tree with feature: Pclass Depth: 6
Making tree with feature: Pclass Depth: 7
Making tree with feature: Pclass Depth: 7
Making tree with feature: Pclass Depth: 4
Making tree with feature: Pclass Depth: 5
Making tree with feature: Age Depth: 5
Making tree with feature: Age Depth: 6
Making tree with feature: Pclass Depth: 7
Making tree with feature: Age Depth: 7
Making tree with feature: Pclass Depth: 6
Making tree with feature: Embarked Depth: 2
Making tree with feature: Fare Depth: 3
Making tree with feature: Parch Depth: 4
Making tree with feature: Embarked Depth: 5
Making tree with feature: Pclass Depth: 6
Making tree with feature: Fare Depth: 6
Making tree with feature: Fare Depth: 7
Making tree with feature: Fare Depth: 7
Making tree with feature: Pclass Depth: 5
Making tree with feature: Fare Depth: 4
Making tree with feature: Fare Depth: 5
Making tree with feature: Fare Depth: 6
Making tree with feature: Pclass Depth: 7
Making tree with feature: Pclass Depth: 7
Making tree with feature: Parch Depth: 6
Making tree with feature: Pclass Depth: 7
Making tree with feature: Age Depth: 7
Making tree with feature: Pclass Depth: 5
Making tree with feature: Fare Depth: 3
Making tree with feature: Fare Depth: 4
Making tree with feature: Age Depth: 5
Making tree with feature: Fare Depth: 6
Making tree with feature: Fare Depth: 7
Making tree with feature: Age Depth: 7
Making tree with feature: SibSp Depth: 6
Making tree with feature: Age Depth: 7
Making tree with feature: Pclass Depth: 7
Making tree with feature: SibSp Depth: 5
Making tree with feature: Pclass Depth: 6
Making tree with feature: Fare Depth: 6
Making tree with feature: Age Depth: 7
Making tree with feature: SibSp Depth: 7
Making tree with feature: SibSp Depth: 4
Making tree with feature: Fare Depth: 5
Making tree with feature: SibSp Depth: 6
Making tree with feature: Age Depth: 7
Making tree with feature: Parch Depth: 7
Making tree with feature: Parch Depth: 6
Making tree with feature: Pclass Depth: 7
Making tree with feature: Age Depth: 7
Making tree with feature: SibSp Depth: 5
Making tree with feature: Pclass Depth: 6
Making tree with feature: Age Depth: 6
Making tree with feature: Fare Depth: 7
Making tree with feature: Pclass Depth: 7
Making tree with feature: Fare Depth: 1
Making tree with feature: Parch Depth: 2
Making tree with feature: Age Depth: 3
Making tree with feature: Embarked Depth: 4
Making tree with feature: Fare Depth: 5
Making tree with feature: Embarked Depth: 6
Making tree with feature: Fare Depth: 7
Making tree with feature: Age Depth: 7
Making tree with feature: Age Depth: 6
Making tree with feature: Age Depth: 7
Making tree with feature: Age Depth: 7
Making tree with feature: Age Depth: 5
Making tree with feature: Fare Depth: 6
Making tree with feature: SibSp Depth: 7
Making tree with feature: Pclass Depth: 7
Making tree with feature: SibSp Depth: 6
Making tree with feature: Fare Depth: 7
Making tree with feature: Pclass Depth: 7
Making tree with feature: Embarked Depth: 4
Making tree with feature: Pclass Depth: 5
Making tree with feature: Pclass Depth: 6
Making tree with feature: Pclass Depth: 6
Making tree with feature: Fare Depth: 5
Making tree with feature: Fare Depth: 6
Making tree with feature: Pclass Depth: 7
Making tree with feature: SibSp Depth: 7
Making tree with feature: Pclass Depth: 6
Making tree with feature: Age Depth: 7
Making tree with feature: Age Depth: 7
Making tree with feature: Age Depth: 3
Making tree with feature: Age Depth: 4
Making tree with feature: SibSp Depth: 5
Making tree with feature: Pclass Depth: 6
Making tree with feature: Pclass Depth: 7
Making tree with feature: Pclass Depth: 7
Making tree with feature: Pclass Depth: 6
Making tree with feature: Age Depth: 5
Making tree with feature: Pclass Depth: 6
Making tree with feature: Pclass Depth: 6
Making tree with feature: Pclass Depth: 7
Making tree with feature: Pclass Depth: 7
Making tree with feature: Embarked Depth: 4
Making tree with feature: Age Depth: 5
Making tree with feature: Pclass Depth: 6
Making tree with feature: Pclass Depth: 6
Making tree with feature: Pclass Depth: 5
Making tree with feature: Pclass Depth: 6
Making tree with feature: Pclass Depth: 6
Making tree with feature: SibSp Depth: 2
Making tree with feature: Age Depth: 3
Making tree with feature: Embarked Depth: 4
Making tree with feature: Pclass Depth: 5
Making tree with feature: Age Depth: 6
Making tree with feature: Fare Depth: 7
Making tree with feature: Age Depth: 7
Making tree with feature: Pclass Depth: 6
Making tree with feature: Fare Depth: 5
Making tree with feature: SibSp Depth: 6
Making tree with feature: Age Depth: 7
Making tree with feature: Pclass Depth: 7
Making tree with feature: SibSp Depth: 6
Making tree with feature: Parch Depth: 7
Making tree with feature: Parch Depth: 7
Making tree with feature: Embarked Depth: 4
Making tree with feature: SibSp Depth: 5
Making tree with feature: Age Depth: 6
Making tree with feature: Parch Depth: 7
Making tree with feature: Pclass Depth: 7
Making tree with feature: Fare Depth: 6
Making tree with feature: Pclass Depth: 7
Making tree with feature: Fare Depth: 7
Making tree with feature: Parch Depth: 5
Making tree with feature: Age Depth: 6
Making tree with feature: Pclass Depth: 7
Making tree with feature: Age Depth: 7
Making tree with feature: Pclass Depth: 6
Making tree with feature: Pclass Depth: 7
Making tree with feature: Pclass Depth: 7
Making tree with feature: SibSp Depth: 3
Making tree with feature: Embarked Depth: 4
Making tree with feature: Pclass Depth: 5
Making tree with feature: Pclass Depth: 6
Making tree with feature: Pclass Depth: 6
Making tree with feature: Pclass Depth: 5
Making tree with feature: SibSp Depth: 6
Making tree with feature: Pclass Depth: 7
Making tree with feature: Pclass Depth: 7
Making tree with feature: Parch Depth: 6
Making tree with feature: Pclass Depth: 7
Making tree with feature: Age Depth: 7
Making tree with feature: Pclass Depth: 4

'Done Training'

## Initializing prediction list

In [ ]:
pred=[]

## Making predictions on test set

In [ ]:
for i in range(test_X.shape[0]):
    output=dt.predict(test_X.loc[i])
    if output == 'Survived':
        pred.append(1)
    else:
        pred.append(0)

## Displaying predictions

In [ ]:
pred

[0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0]

## Extracting true labels

In [ ]:
label= test_X['Survived']

## Displaying true labels

In [ ]:
label

0      1
1      0
2      0
3      0
4      1
      ..
174    0
175    1
176    0
177    1
178    0
Name: Survived, Length: 179, dtype: int64

## Calculating accuracy

In [ ]:
corr = 0

for i in range(label.shape[0]):
    print(pred[i], label[i])
    if pred[i]== label[i]:
        corr+=1

print( corr / label.shape[0])

0 1
0 0
0 0
0 0
1 1
1 1
0 0
0 0
1 1
0 0
0 0
0 0
0 1
0 0
1 1
1 1
0 0
1 0
1 1
0 0
0 0
0 0
0 0
0 0
0 0
0 1
0 0
0 0
1 1
1 0
1 1
0 0
0 1
0 0
0 0
1 1
0 0
0 0
1 1
1 1
0 0
0 0
1 1
1 1
0 0
0 0
0 0
1 1
0 0
0 0
0 1
1 1
0 0
1 1
0 0
1 0
0 0
0 0
0 0
0 0
1 0
0 0
1 1
0 0
0 0
1 1
0 0
1 1
1 1
1 1
1 0
0 0
0 0
0 0
1 1
0 0
1 1
0 0
0 0
0 0
0 0
0 0
0 0
0 0
1 1
0 1
0 0
1 0
0 0
1 1
1 1
1 1
0 1
0 0
0 0
1 0
0 0
1 1
0 0
0 0
0 0
0 0
0 0
0 0
1 0
0 0
0 0
0 0
1 1
0 1
0 0
1 1
0 0
0 0
1 0
0 1
0 1
1 1
0 1
1 1
0 0
0 0
0 0
1 1
0 0
0 0
1 1
0 1
0 0
0 0
1 1
0 0
0 0
0 0
0 0
0 0
1 0
1 1
0 0
0 0
1 0
1 1
1 0
0 1
1 1
0 1
1 1
0 0
0 0
0 0
1 1
0 0
0 0
1 1
1 1
1 0
0 0
1 1
0 0
1 1
0 0
0 0
1 1
1 1
0 0
0 0
0 0
0 1
1 1
0 0
0 0
0 0
0 0
1 0
0 0
1 1
1 0
1 1
0 0
0.8324022346368715